--- 
abstract: A curses based OO user interface framework
author: 
  - Shawn Boyette C<< <mdxi@cpan.org> >>
build_requires: 
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Curses-UI
no_index: 
  directory: 
    - examples
    - inc
    - t
requires: 
  Curses: 0
  Term::ReadKey: 0
version: 0.9603
