---
abstract: 'A curses based OO user interface framework'
author:
  - 'Shawn Boyette C<< <mdxi@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Curses-UI
no_index:
  directory:
    - examples
    - inc
    - t
    - examples
requires:
  Curses: 0
  Term::ReadKey: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.9606
