#!/usr/bin/perl -w
use strict;

# We do not want STDERR to clutter our screen.
open STDERR, ">/dev/null";

use FindBin;
use lib "$FindBin::RealBin/../lib";
use Curses::UI;
my $cui = new Curses::UI;

my $win = $cui->add('window_id', 'Window');

$win->add(
        'mylabel', 'Label',
        -text      => 'Hello, world!',
        -width     => -1,
	-border    => 1,
        -textalignment => 'middle',
);

$win->add(
        'nopadspace', 'Label',
        -text      => 'Without -paddingspaces set',
        -width     => -1,
	-border    => 1,
	-y         => 3,
	-reverse   => 1,
	-paddingspaces => 0,
);

$win->add(
        'yespadspace', 'Label',
        -text      => 'With -paddingspaces set',
        -width     => -1,
	-border    => 1,
	-y         => 6,
	-reverse   => 1,
	-paddingspaces => 1,
);


my $l = $win->add(
        'mylabel2', 'Label',
	-y         => 9,
        -width     => -1,
	-border    => 1,
);

$win->draw;

my @allfonts = qw(-bold -dim -reverse -underline -blink);
my @allalignments = qw(left middle right);

foreach my $font (@allfonts) {
    $l->set_attribute($font, 1);
    foreach my $align (@allalignments) {
	$l->textalignment($align);
	$l->text("Font: $font, Alignment: $align");
	$l->draw;
	sleep 1;
    }
    $l->set_attribute($font, 0);
}


