#!/usr/bin/perl -w
use strict;

use FindBin;
use lib "$FindBin::RealBin/../lib";
use Curses::UI;

my $debug = 0;
if (@ARGV and $ARGV[0] eq '-d') {
    open STDERR, ">>/tmp/Curses::UI_debug";
    $debug = 1;
} else {
    # We do not want STDERR to clutter our screen.
    open STDERR, ">/dev/null";
}


my $cui = new Curses::UI (
    -clear_on_exit => 1,
    -language      => 'Dutch',
    -debug         => $debug,
);

$cui->dialog(
      "This demo shows how easy the language for an application\n"
    . "can be set. This application is set to Dutch and if you close\n"
    . "this dialog, a Dutch filebrowser will be shown (all labels, titles\n"
    . "and error messages are in Dutch). Of course this filebrowser\n"
    . "will not actually write a file.");

$cui->savefilebrowser();

