#!/usr/bin/perl -w use strict;

# Deny STDERR
open STDERR, ">/dev/null";


use FindBin;
use lib "$FindBin::RealBin/../lib";
use Curses::UI;
my $cui = new Curses::UI ( -clear_on_exit => 1 );

my $file = $cui->filebrowser(
	-title => 'demo filebrowser',
	-path => '/',
	-show_hidden => 0,
	-mask => [
            [ '^.*$',     'All files'              ],
     	    [ '.txt$',    'Textfiles (*.txt)'      ],
	    [ '.doc$',    'Document files (*.doc)' ],
	    [ '^README$', 'Readme files'           ],
        ],
        -mask_selected => 0,
        -editfilename => 1,
);

$cui->rebuild_from_scratch;
$cui->dialog("selected file: $file") if defined $file;;

