#!/usr/bin/perl -w use strict;

# Deny STDERR
open STDERR, ">/dev/null";

use FindBin;
use lib "$FindBin::RealBin/../lib";
use Curses::UI;
my $cui = new Curses::UI ( -clear_on_exit => 1 );

$cui->dialog(
	-message => "The most simple dialog"
);

$cui->draw;

my $pressed = $cui->dialog(
	-message => "Some extra buttons",
	-buttons => [ 
	    {-label => '< Yeah, so? >', -value => 'first'}, 
            {-label => '< Why would I care? >', -value => 'second'},
	],
);

$cui->draw;

$cui->dialog(
	-message => "I don't know but you pressed\n"
                  . "the $pressed button",
	-buttons => [ {-label => '< Allright, get me outta here! >'} ]
);

$cui->draw;

$cui->dialog(
	-message => "At your command, my lord"
);

